<?php
declare (strict_types=1);

namespace app\model;

use think\Model;

/**
 * @mixin \think\Model
 */
class BaseModel extends Model
{

    const STATUS_SHOW = 1;//显示
    const STATUS_HIDE = 0;//隐藏
    const IS_HOT = 1;//是否热门

    public static $imageUrl = '';
    public  function init()
    {
        self::$imageUrl = TC('goods_image_url');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function pageOne($map=[],$field='*',$cache=0){
        $sql= self::where($map)->field($field);
        if ($cache > 0){
            $sql = $sql->cache($cache);
        }
        return $sql->find();
    }

    public static function pageUpdate($map=[],$data= []){
        return self::where($map)->update($data);
    }
    public static function pageOneValue($map=[],$field='id',$cache=0){
        $sql= self::where($map);
        if ($cache > 0){
            $sql = $sql->cache($cache);
        }
        return $sql->value($field);
    }

    public static function pageOneColumn($map=[],$field='id',$cache=0){
        $sql= self::where($map);
        if ($cache > 0){
            $sql = $sql->cache($cache);
        }
        return $sql->column($field);
    }
    public static function pageList($map=[],$field='*',$order=[],$cache=0){
        $sql = self::where($map)->field($field);
        if ($cache > 0){
            $sql = $sql->cache($cache);
        }
        if (!empty($order)){
            $sql = $sql->order($order);
        }
        return $sql->select();
    }
    public static function inserts($data = []){
        return self::insertGetId($data);
    }

    public static function pageLimitList($map = [], $page = 1, $limit = 10, $order = [], $cache = 0, $field = '*')
    {
        $sql = self::where($map);
        if (!empty($order)){
            $sql = $sql->order($order);
        }
        if ($cache>0){
            $sql = $sql->cache($cache);
        }

        return $sql->field($field)->paginate([
                                                 'list_rows'=> $limit,
                                                 'page' => $page,
                                             ]);
    }
}
