<?php

namespace app\admin\controller\v1;

use app\admin\controller\Base;
use app\common\model\UserModel as models;
use app\validate\User as validates;
use think\exception\ValidateException;

class User extends Base
{
    protected $model;

    public function initialize ()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //获取列表信息
    public function index ()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map  = [];
        isset($post['user_name']) && $map [] = ['b.user_name', 'like', '%' . $post['user_name'] . '%'];
        isset($post['phone']) && $map[] = ['b.phone', '=', $post['phone']];
        isset($post['user_team']) && $map [] = ['b.user_team', '=', $post['user_team']];
        isset($post['agent_1']) && $map [] = ['b.agent_id_1', '=', $post['agent_1']];
        isset($post['agent_2']) && $map [] = ['b.agent_id_2', '=', $post['agent_2']];
        isset($post['agent_3']) && $map [] = ['b.agent_id_3', '=', $post['agent_3']];
        isset($post['start']) && $map [] = ['b.create_time', '>=', $post['start']]; //注册IP少选
        isset($post['end']) && $map [] = ['b.create_time', '<', $post['end']]; //注册IP少选

        $list = $this->model->page_list($map, $limit, $page);
        return $this->success($list);
    }

    public function add ()
    {
        //过滤数据
        $postField = 'is_fictitious,user_name,sfz,phone,pwd,withdraw_pwd,market_uid,agent_id,is_audit';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $post['market_uid'] =1;
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }
        //查询是否重复的用户名
        $find = $this->model->where('user_name', $post['user_name'])->whereOr('phone', $post['phone'])->find();
        if ($find)
            return $this->failed('用户已存在');

        //加密密码
        $post['pwd'] = !empty($post['pwd']) && isset($post['pwd']) ? md5($post['pwd']) : home_Initial_pwd();

        if (!empty($post['withdraw_pwd'])) {
            $post['withdraw_pwd'] = base64_encode(123456);
        }

        if (isset($post['agent_id']) && $post['agent_id'] > 0) {
            //查询用户是否存在
            $agent_info = $this->model->where('id', $post['agent_id'])->find();
            if (empty($agent_info)) {
                return $this->failed('代理不存在');
            }
            $post['user_team'] = $agent_info['user_team'];
            $post['agent_id_1'] = $agent_info['id'];
            $post['agent_id_2'] = $agent_info['agent_id_1'];
            $post['agent_id_3'] = $agent_info['agent_id_2'];
        } else {
            $post['user_team'] = UserTeam();
        }
        //获取ID
        $post['head_img'] = '/static/touxiang/' . rand(1, 20) . '.jpg';
        $post['ip'] = $this->request->ip();
        //执行修改数据

        $save = $this->model->save($post);
        if ($save)
            return $this->success([]);
        return $this->failed('修改失败');
    }
}