<?php


namespace app\agent\controller;

use app\BaseController;
use app\common\model\TokenModel;
use app\common\model\UserModel;
use app\middleware\Agent;
use app\middleware\Before;

//需要验证

class Base extends BaseController
{
    protected $middleware = [Agent::class, Before::class,];//验证token和访问控制器权利

    public function initialize ()
    {
        $request = $this->request;
        $token = $request->post('token');
        if (empty($token)) {
            $token = $request->param('token');
        }
        if (empty($token))
            return $this->failed('token不存在');
        //校验是否过期的token
        //$type 1后台用户 2代理商后台
        $map['type'] = 2;
        $map['token'] = $token;
        $res = (new TokenModel())->where($map)->find();
        if (empty($res))
            return $this->failed('无效token');

        $expiration_time = time() - strtotime($res['create_time']);
        if ($expiration_time >= env('token.token_time', 10))
            return $this->failed('token过期');
        session('admin_agent_user', UserModel::where('id', '=', $res['admin_uid'])->find());
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}